---
name: apply

on:
  push:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
  AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
  AWS_DEFAULT_REGION: us-east-1
  NEW_RELIC_ACCOUNT_ID: "${{ secrets.NEW_RELIC_ACCOUNT_ID }}"
  NEW_RELIC_API_KEY: "${{ secrets.NEW_RELIC_API_KEY }}"


jobs:
  apply:
    name: apply
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: terraform apply
        uses: dflook/terraform-apply@v1
        with:
          path: newrelic/synthetics
