# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:

env:
  NEW_RELIC_ACCOUNT_ID: "${{ secrets.NEW_RELIC_ACCOUNT_ID }}"
  #NEW_RELIC_API_KEY: "${{ secrets.NEW_RELIC_API_KEY }}"


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Validate terraform (with the side-effect of installing the right
    # version of terraform based on required_version constraints)
    - name: validate
      uses: dflook/terraform-validate@v1
      with:
        path: newrelic/synthetics

    - name: fmt
      uses: dflook/terraform-fmt-check@v1
      with:
        path: newrelic/synthetics

    # Runs terraform lint
    - name: lint
      uses: actionshub/terraform-lint@main

    - name: security scan
      uses: triat/terraform-security-scan@v2.2.3
      with:
        tfsec_actions_working_dir: ./newrelic # optional, default is .
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
